# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Herald Project
email: adam@adamfowler.org
author: Herald Project Contributors
description: >- # this means to ignore newlines until "baseurl:"
  The home for our research in to low level mobile phone Bluetooth
  capabilities, issues, workarounds, and testing.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://theheraldproject.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: /img/herald.png
gh_repo: https://github.com/theheraldproject/theheraldproject.github.io
#markdown: redcarpet
hero:
  background-color: med-blue
footer:
  title: Getting Started
  content: To help you get started, see the documentation.
  cta_title:
  cta_url: /docs
  cta_text: Documentation

footer_social_links:
  Twitter:
    fa_icon: fab fa-twitter
    url: https://twitter.com/HeraldProximity
  Slack:
    fa_icon: fab fa-slack
    url: https://slack.lfph.io/
  RSS:
    fa_icon: fa fa-rss
    url: feed.xml
  GitHub:
    fa_icon: fab fa-github
    url: https://github.com/theheraldproject

collections:
  - contributors
  - casestudies

# Build settings
#theme: bulma-clean-theme 
#remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-feed
  - github-pages
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-relative-links # Used to auto generate md links to html links
  - jekyll-optional-front-matter # Parse Markdown files that do not have front-matter callouts
  - jekyll-readme-index # use README.md as index.html
  - jekyll-titles-from-headings # pull the page title from the first Markdown heading when none is specified.
  - jekyll-paginate # pagination object for collections (e.g. posts)
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-spaceship

permalink: /blog/:title
sass:
  sass_dir: css
  style: :compressed

# Blog properties
paginate: 10
paginate_path: "/blog/page:num"

# Site defaults
defaults:
  -
    values:
      layout: page
      hero_height: "is-small"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - NOTICE.txt
  - LICENSE.txt
  - .gitignore
  - code_of_conduct.md
  - contributing.md
  - .travis.yml
  - cibuild
  - .github

#redcarpet:
#    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
